# Generated by Django 3.0.4 on 2020-03-12 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('apellido', models.CharField(default='', max_length=20)),
                ('documento', models.CharField(default='', max_length=8)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('tipoUsuario', models.IntegerField(default=0)),
                ('dirDepartamento', models.CharField(default='', max_length=20, verbose_name='Departamento')),
                ('dirCiudad', models.CharField(default='', max_length=20)),
                ('dirCalle', models.CharField(default='', max_length=50)),
                ('dirNumero', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Azul', 'Azul'), ('Bordó', 'Bordó'), ('Marrón', 'Marrón'), ('Gris_Plata', 'Gris Plata'), ('Gris_Ceniza', 'Gris Ceniza'), ('Amarillo', 'Amarillo'), ('Verde', 'Verde'), ('Otro', 'Otro')], max_length=15)),
                ('nroChasis', models.CharField(default='', max_length=50)),
                ('matricula', models.CharField(default='', max_length=50)),
                ('anio', models.IntegerField(default=0)),
                ('tipoCombustible', models.CharField(blank=True, choices=[('Nafta', 'Nafta'), ('Gasoil', 'Gasoil'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico'), ('Hidrógeno', 'Hidrógeno'), ('GLP', 'Glp')], max_length=15)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Usuario')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default='10/10/2020 22:22:00')),
                ('textoOtros', models.CharField(default='', max_length=240)),
                ('comentario', models.CharField(default='', max_length=240)),
                ('kilometros', models.IntegerField(default=0)),
                ('puntuacion', models.IntegerField(default=0)),
                ('costo', models.IntegerField(default=0)),
                ('estados', models.ManyToManyField(through='webapp.Estado_Servicio', to='webapp.Estado')),
                ('tareas', models.ManyToManyField(to='webapp.Tarea')),
                ('vehiculo', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='estado_servicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Servicio'),
        ),
    ]
