# Generated by Django 3.0.4 on 2020-03-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=8)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipoUsuario', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
