# Generated by Django 3.0.4 on 2020-03-12 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2020, 3, 12, 9, 4, 40, 534699))),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Servicio')),
            ],
        ),
        migrations.DeleteModel(
            name='Estado_Servicio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estados',
            field=models.ManyToManyField(through='webapp.EstadoServicio', to='webapp.Estado'),
        ),
    ]
