# Generated by Django 3.0.4 on 2020-03-13 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 13, 14, 28, 433470)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='textoOtros',
            field=models.TextField(default='', max_length=240),
        ),
    ]
