# Generated by Django 3.0.4 on 2020-04-11 15:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={'get_latest_by': 'fecha'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='estadoAc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(default='', max_length=240, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 12, 25, 15, 554017)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estados',
            field=models.ManyToManyField(through='webapp.EstadoServicio', to='webapp.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='kilometros',
            field=models.IntegerField(default=0, verbose_name='Kilómetros'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='puntuacion',
            field=models.IntegerField(default=0, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='textoOtros',
            field=models.TextField(blank=True, default='', max_length=240, verbose_name='Otras tareas'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirCalle',
            field=models.CharField(default='', max_length=50, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirCiudad',
            field=models.CharField(default='', max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirDepartamento',
            field=models.CharField(choices=[('Artigas', 'Artigas'), ('Canelones', 'Canelones'), ('Cerro_Largo', 'Cerro Largo'), ('Colonia', 'Colonia'), ('Durazno', 'Durazno'), ('Flores', 'Flores'), ('Florida', 'Florida'), ('Lavalleja', 'Lavalleja'), ('Maldonado', 'Maldonado'), ('Montevideo', 'Montevideo'), ('Paysandú', 'Paysandú'), ('Río_Negro', 'Río Negro'), ('Rivera', 'Rivera'), ('Rocha', 'Rocha'), ('Salto', 'Salto'), ('San_José', 'San José'), ('Soriano', 'Soriano'), ('Tacuarembó', 'Tacuarembó'), ('Treinta_y_Tres', 'Treinta Y Tres')], default='', max_length=20, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirNumero',
            field=models.CharField(default='', max_length=5, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(default=1, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(default=2020, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='duenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(default='', max_length=50, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='nroChasis',
            field=models.CharField(default='', max_length=50, verbose_name='Número de chasis'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipoCombustible',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Nafta', 'Nafta'), ('Gasoil', 'Gasoil'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico'), ('Hidrógeno', 'Hidrógeno'), ('GLP', 'Glp')], default='Ninguno', max_length=15, verbose_name='Tipo de combustible'),
        ),
    ]
