# Generated by Django 3.0.4 on 2020-03-15 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200313_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 13, 12, 23, 677360)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estados',
            field=models.ManyToManyField(through='webapp.EstadoServicio', to='webapp.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='textoOtros',
            field=models.TextField(default='', max_length=240, verbose_name='Otras tareas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirDepartamento',
            field=models.CharField(choices=[('Artigas', 'Artigas'), ('Canelones', 'Canelones'), ('Cerro_Largo', 'Cerro Largo'), ('Colonia', 'Colonia'), ('Durazno', 'Durazno'), ('Flores', 'Flores'), ('Florida', 'Florida'), ('Lavalleja', 'Lavalleja'), ('Maldonado', 'Maldonado'), ('Montevideo', 'Montevideo'), ('Paysandú', 'Paysandú'), ('Río_Negro', 'Río Negro'), ('Rivera', 'Rivera'), ('Rocha', 'Rocha'), ('Salto', 'Salto'), ('San_José', 'San José'), ('Soriano', 'Soriano'), ('Tacuarembó', 'Tacuarembó'), ('Treinta_y_Tres', 'Treinta Y Tres')], default='', max_length=20, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.IntegerField(default=1),
        ),
    ]
