# Generated by Django 3.0.4 on 2020-03-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_estado_servicio_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='estado',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='kilometros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='tareas',
            field=models.ManyToManyField(to='webapp.Tarea'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='textoOtros',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dirCalle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dirCiudad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dirDepartamento',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dirNumero',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='estado',
            name='descripcion',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='comentario',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Azul', 'Azul'), ('Bordó', 'Bordó'), ('Marrón', 'Marrón'), ('Gris_Plata', 'Gris Plata'), ('Gris_Ceniza', 'Gris Ceniza'), ('Amarillo', 'Amarillo'), ('Verde', 'Verde'), ('Otro', 'Otro')], max_length=15)),
                ('nroChasis', models.CharField(default='', max_length=50)),
                ('matricula', models.CharField(default='', max_length=50)),
                ('anio', models.IntegerField(default=0)),
                ('tipoCombustible', models.CharField(blank=True, choices=[('Nafta', 'Nafta'), ('Gasoil', 'Gasoil'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico'), ('Hidrógeno', 'Hidrógeno'), ('GLP', 'Glp')], max_length=15)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Usuario')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Estado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='estados',
            field=models.ManyToManyField(through='webapp.Estado_Servicio', to='webapp.Estado'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='vehiculo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehiculo'),
        ),
    ]
