# Generated by Django 3.0.3 on 2020-03-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200306_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCombustible',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehiculo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dirDepartamento',
            field=models.CharField(default='', max_length=20, verbose_name='Departamento'),
        ),
    ]
