# Generated by Django 3.0.4 on 2020-03-15 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200315_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 55, 11, 372137)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
