# Generated by Django 3.0.4 on 2020-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200311_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_servicio',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
