# Generated by Django 3.0.4 on 2020-03-17 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200315_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 18, 30, 45, 432037)),
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='estados',
        ),
        migrations.AddField(
            model_name='servicio',
            name='estados',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='webapp.Estado', verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(default=2020),
        ),
    ]
