# Generated by Django 3.0.4 on 2020-03-28 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200327_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoservicio',
            options={'get_latest_by': 'fecha'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='estadoAc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 28, 14, 56, 59, 514373)),
        ),
    ]
