# Generated by Django 3.0.4 on 2020-04-04 00:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200328_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 21, 44, 6, 433550)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Vehiculo', verbose_name='Vehículo'),
        ),
    ]
