# Generated by Django 3.0.4 on 2020-04-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20200409_2028'),
        ('webapp', '0013_auto_20200409_1829'),
    ]

    operations = [
    ]
