# Generated by Django 3.0.4 on 2020-04-16 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_merge_20200414_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 22, 7, 21, 422333)),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipoCombustible',
            field=models.CharField(choices=[('Nafta', 'Nafta'), ('Gasoil', 'Gasoil'), ('Híbrido', 'Híbrido'), ('Eléctrico', 'Eléctrico'), ('Hidrógeno', 'Hidrógeno'), ('GLP', 'Glp')], default='Ninguno', max_length=15, verbose_name='Tipo de combustible'),
        ),
    ]
