# Generated by Django 3.0.4 on 2020-04-17 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20200416_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoservicio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 22, 37, 13, 513064)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/default.jpg', upload_to='media/avatar'),
        ),
    ]
